version: '3'

services:
  psql:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=nibbler
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nibbler:
    image: krak3n/nibbler:latest
    links:
      - "psql:psql"
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_HOST=psql
      - DB_NAME=nibbler
      - DB_SSL_MODE=disable
    ports:
      - "127.0.0.1:3000:3000"
